name: Deploy to Server

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - main

env:
  SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP << 'EOF'
            cd /app
            git pull origin main
          EOF

      - name: "Install dependencies"
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP << 'EOF'
            cd /app
            docker run --rm --volume /app:/app composer install --ansi --no-interaction --no-progress
          EOF
      
      - name: "Build and compile assets"
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP << 'EOF'
            docker exec my-php-demo-app php /var/www/html/bin/console importmap:install
            docker exec my-php-demo-app php /var/www/html/bin/console sass:build
            docker exec my-php-demo-app php /var/www/html/bin/console asset-map:compile
          EOF